server:
  port: 9293
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@activatedProperties@'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka-discovery/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

spring.cloud.gateway.discovery.locator.enabled: true
spring.cloud.gateway.discovery.locator.lower-case-service-id: true

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: beta
  application.name: api-gateway

server.servlet.context-path: '/api-gateway'
eureka.client.service-url:
  defaultZone: http://eureka_discovery:9090/eureka-discovery/eureka