version: "3.6"

services:

  microservice_user:
    image: microservice_user
    container_name: microservice_user
    hostname: microservice_user
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        PROJECT_NAME: microservice-user
        PORT: 9092
    ports:
      - "9092:9092"
    networks:
      - network_java

  eureka_discovery:
    image: eureka_discovery
    container_name: eureka_discovery
    hostname: eureka_discovery
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        PROJECT_NAME: eureka-discovery
        PORT: 9090
    ports:
      - "9090:9090"
    networks:
      - network_java

networks:
  network_java:
    name: network_java