version: "3.6"

services:

  java_micro_service:
    image: java_micro_service
    container_name: java_micro_service
    hostname: java_micro_service
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "9292:9292"
    networks:
      - network_java


networks:
  network_java:
    name: network_java