server:
  port: 9090
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@activatedProperties@'

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9090/${spring.application.name}/eureka

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: beta
  application.name: eureka-discovery


server.servlet.context-path: '/eureka-discovery'
eureka.client.service-url:
  defaultZone: http://eureka_discovery:9090/eureka-discovery/eureka