server:
  port: 9092
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@activatedProperties@'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka-discovery/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    instance-id: ${spring.application.name}-${server.port}

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 0
---
spring:
  config:
    activate:
      on-profile: beta
  application.name: microservice

#TODO PORQUE CUANDO CREO LA IMAGEN NO TOMA LOS VALORES DECLARADOS EN EL POM EXAMPLE app.context-path
server.servlet.context-path: '/microservice-user'
eureka.client.service-url:
  defaultZone: http://eureka_discovery:9090/eureka-discovery/eureka